// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sastreria_data.database.tables;

#nullable disable

namespace WebSastreria.Migrations
{
    [DbContext(typeof(_dbContext))]
    [Migration("20251105032310_AddModeloCategoriaRelation")]
    partial class AddModeloCategoriaRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriaModelo", b =>
                {
                    b.Property<int>("CategoriasIdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("ModelosIdModelo")
                        .HasColumnType("int");

                    b.HasKey("CategoriasIdCategoria", "ModelosIdModelo");

                    b.HasIndex("ModelosIdModelo");

                    b.ToTable("ModeloCategoria", (string)null);
                });

            modelBuilder.Entity("sastreria_data.database.tables.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__A3C02A1032B13906");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("sastreria_data.database.tables.CitaImagen", b =>
                {
                    b.Property<int>("IdCitaImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCitaImagen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCitaImagen"));

                    b.Property<int>("IdCita")
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("IdCita");

                    b.Property<string>("Url")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageUrl");

                    b.HasKey("IdCitaImagen");

                    b.ToTable("CitaImagen");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Citum", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcita");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("state");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("datetime2")
                        .HasColumnName("citafecha");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idcliente");

                    b.Property<string>("Notas")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("notes");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("PedidoId");

                    b.HasKey("IdCita")
                        .HasName("PK__Cita__394B02026E23F138");

                    b.HasIndex("IdCliente");

                    b.HasIndex("PedidoId");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("lastname");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("idtipodocumento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("name");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numerodocumento");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("phonenumber");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__D5946642D6F2BE01");

                    b.HasIndex("IdTipoDocumento");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Dato", b =>
                {
                    b.Property<int>("IdDatos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddatosastreria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatos"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("address");

                    b.Property<string>("LogoSastreria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("picture");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("phonenumber");

                    b.HasKey("IdDatos")
                        .HasName("PK__Datos__A4BC7BC551DEEEC5");

                    b.ToTable("DatoSastreria");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("IdEstado")
                        .HasName("PK__Estado__FBB0EDC135F48D85");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idhorario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("day");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("state");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("horafin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("horainicio");

                    b.HasKey("IdHorario")
                        .HasName("PK__Horario__1539229B8DE62D0D");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creationdate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("IdModelo")
                        .HasName("PK__Modelo__CC30D30CD4075261");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("sastreria_data.database.tables.ModeloImagen", b =>
                {
                    b.Property<int>("IdModeloImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModeloImagen"));

                    b.Property<int>("IdModelo")
                        .HasColumnType("int")
                        .HasColumnName("idmodelo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("IdModeloImagen")
                        .HasName("PK__ModeloIm__75E9782729A4E057");

                    b.HasIndex("IdModelo");

                    b.ToTable("ModeloImagen");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idpedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("Detalle")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("details");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaentrega");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idcliente");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("idestado");

                    b.Property<int?>("IdModelo")
                        .HasColumnType("int")
                        .HasColumnName("idmodelo");

                    b.Property<int?>("IdSastre")
                        .HasColumnType("int")
                        .HasColumnName("idsastre");

                    b.HasKey("IdPedido")
                        .HasName("PK__Pedido__9D335DC383EAADC3");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdModelo");

                    b.HasIndex("IdSastre");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Sastre", b =>
                {
                    b.Property<int>("IdSastre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSastre"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("name");

                    b.HasKey("IdSastre")
                        .HasName("PK__Sastre__06563E870BA6D5DE");

                    b.ToTable("Sastre");
                });

            modelBuilder.Entity("sastreria_data.database.tables.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("IdTipoDocumento")
                        .HasName("PK__TipoDocu__3AB3332FE8CECEF4");

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("CategoriaModelo", b =>
                {
                    b.HasOne("sastreria_data.database.tables.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sastreria_data.database.tables.Modelo", null)
                        .WithMany()
                        .HasForeignKey("ModelosIdModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sastreria_data.database.tables.Citum", b =>
                {
                    b.HasOne("sastreria_data.database.tables.Cliente", "IdClienteNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Cita__IdCliente__5441852A");

                    b.HasOne("sastreria_data.database.tables.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Cliente", b =>
                {
                    b.HasOne("sastreria_data.database.tables.TipoDocumento", "IdTipoDocumentoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdTipoDocumento")
                        .IsRequired()
                        .HasConstraintName("FK__Cliente__IdTipoD__45F365D3");

                    b.Navigation("IdTipoDocumentoNavigation");
                });

            modelBuilder.Entity("sastreria_data.database.tables.ModeloImagen", b =>
                {
                    b.HasOne("sastreria_data.database.tables.Modelo", "IdModeloNavigation")
                        .WithMany("ModeloImagenes")
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdModeloNavigation");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Pedido", b =>
                {
                    b.HasOne("sastreria_data.database.tables.Cliente", "IdClienteNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Pedido__IdClient__49C3F6B7");

                    b.HasOne("sastreria_data.database.tables.Estado", "IdEstadoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK__Pedido__IdEstado__4AB81AF0");

                    b.HasOne("sastreria_data.database.tables.Modelo", "IdModeloNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdModelo")
                        .HasConstraintName("FK__Pedido__IdModelo__4BAC3F29");

                    b.HasOne("sastreria_data.database.tables.Sastre", "IdSastreNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdSastre")
                        .HasConstraintName("FK__Pedido__IdSastre__48CFD27E");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdModeloNavigation");

                    b.Navigation("IdSastreNavigation");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Cliente", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Estado", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Modelo", b =>
                {
                    b.Navigation("ModeloImagenes");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("sastreria_data.database.tables.Sastre", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("sastreria_data.database.tables.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
